{% set name = "roct-thunk-interface" %}
{% set version = "6.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCT-Thunk-Interface/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 097a5b7eb136300667b36bd35bf55e4a283a1ed04e614cf24dddca0a65c86389

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
    - pkg-config
  host:
    - libdrm
  run:

test:
  commands:
    - test -f $PREFIX/include/hsakmt/hsakmt.h
    - test -f $PREFIX/lib/libhsakmt.so

about:
  home: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Radeon Open Compute Thunk Interface'

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
