{% set name = "roct-thunk-interface" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/roc-{{ version }}.tar.gz
  sha256: b08176b5f4af39d0160990f9f1dea5d27974f9282f544140b4a41d19446fe570

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
    - pkg-config
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/hsakmt.h
    - test -f $PREFIX/lib/libhsakmt.so

about:
  home: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Radeon Open Compute Thunk Interface

extra:
  recipe-maintainers:
    - isuruf
