{% set name = "roct-thunk-interface" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/ROCT-Thunk-Interface/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 5354bda9382f80edad834463f2c684289841770a4f7b13f0f40bd8271cc4c71d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libdrm
  run:

test:
  commands:
    - test -f $PREFIX/include/hsakmt/hsakmt.h
    - test -f $PREFIX/lib/libhsakmt.so

about:
  home: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Radeon Open Compute Thunk Interface'

extra:
  recipe-maintainers:
    - isuruf
