{% set name = "roct-thunk-interface" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/roc-{{ version }}.tar.gz
  sha256: f709be7cb820d92544b0926426b2ea5ebb66c558d2efe5acde604592cda94046

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ cdt('numactl-devel') }}
    - {{ cdt('pciutils-devel') }}
    - pkg-config
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/hsakmt.h
    - test -f $PREFIX/lib/libhsakmt.so

about:
  home: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Radeon Open Compute Thunk Interface'

extra:
  recipe-maintainers:
    - isuruf
